[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
startup_mode = "Windowed"
opacity = 1

[window.dimensions]
columns = 160
lines = 50

[window.padding]
x = 16
y = 16

[general]
live_config_reload = true
