[font]
size = 14

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Lilex Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
