[colors.bright]
black = "#323232"
blue = "#b4c8fa"
cyan = "#b4e8eb"
green = "#c8f0c1"
magenta = "#e0c6f7"
red = "#f8bcc8"
white = "#ffffff"
yellow = "#faf0cf"

[colors.normal]
black = "#242424"
blue = "#a0b4da"
cyan = "#a0d4db"
green = "#b0d8a1"
magenta = "#c8b0e7"
red = "#d8a0b8"
white = "#ffffff"
yellow = "#e0d4af"

[colors.dim]
black = "#4a4a4a"
blue = "#c0d0f0"
cyan = "#c0e0e0"
green = "#d0e8c8"
magenta = "#e8d0f8"
red = "#f0c0d0"
white = "#161616"
yellow = "#f8e8d0"

[colors.primary]
background = "#161616"
foreground = "#f8f8f6"

dim_foreground = "#4a4a4a"
bright_foreground = "#ffffff"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"
