[colors.bright]
black = "#323232"
blue = "#b4c8fa"
cyan = "#87BAC3"
green = "#DDEB9D"
magenta = "#e0c6f7"
red = "#f8bcc8"
white = "#1F2937"
yellow = "#E4E0E1"

[colors.normal]
black = "#242424"
blue = "#a0b4da"
cyan = "#53629E"
green = "#8AA624"
magenta = "#c8b0e7"
red = "#F08787"
white = "#4B5563"
yellow = "#E2A16F"

[colors.dim]
black = "#a5a5a5"
blue = "#c0d0f0"
cyan = "#A9B5DF"
green = "#DBE4C9"
magenta = "#e8d0f8"
red = "#f0c0d0"
white = "#6B7280"
yellow = "#f8e8d0"

[colors.primary]
background = "#f2ebe2"
foreground = "#161616"

dim_foreground = "#4a4a4a"
bright_foreground = "#000000"

[colors.cursor]
cursor = "#4a4a4a"
text = "#f2ebe2"
